services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: (à générer avec `php artisan key:generate --show`)
      - key: DB_HOST
        value: (host fourni par Railway ou PlanetScale, ou Render DB)
      - key: ...
