services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: ./start.sh
    secretFiles:
      - key: .env
        name: .env
